-- =====================================================
-- DATA OBJEK WISATA
-- Risk Assessment Objek Wisata
-- Dari: DATA WISATA ,OBVITNAS & OBVITER-1.pdf
-- Wilayah: Polres Samosir
-- =====================================================

USE risk_assessment_db;

INSERT INTO objek_wisata (nama, alamat) VALUES
('Pantai Pasir Putih Parbaba', 'Lokasi: Parbaba/Samosir | Jenis: Wisata Alam | Wilayah: Polres Samosir | Keterangan: Kawasan Ekonomi Khusus'),
('Pantai Indah Situngkir', 'Lokasi: Situngkir/Samosir | Jenis: Wisata Alam | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Pantai Tanda Rabun', 'Lokasi: Desa Dos roha/Samosir | Jenis: Wisata Alam | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Pantai Batu Hoda', 'Lokasi: Simanindo/Samosir | Jenis: Wisata Alam | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Huta Sialagan', 'Lokasi: Siallagan/Samosir | Jenis: Wisata Alam, Wisata Sejarah dan Budaya | Wilayah: Polres Samosir | Keterangan: Kawasan Ekonomi Khusus'),
('Patung Si Gale-gale', 'Lokasi: Tomok/Samosir | Jenis: Wisata Sejarah dan Budaya | Wilayah: Polres Samosir | Keterangan: Kawasan Ekonomi Khusus'),
('Kawasan Tomok', 'Lokasi: Tomok/Samosir | Jenis: Wisata Belanja | Wilayah: Polres Samosir | Keterangan: Kawasan Ekonomi Khusus'),
('Air Terjun Efrata', 'Lokasi: Harian/Samosir | Jenis: Wisata Alam | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Pantai Pandua', 'Lokasi: Nainggolan/Samosir | Jenis: Wisata Alam | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Pantai Indah Sipinggan', 'Lokasi: Sipinggan/Samosir | Jenis: Wisata Alam | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Danau Aek Natonang', 'Lokasi: Tanjungan/Samosir | Jenis: Wisata Alam | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Dermaga Jetty', 'Lokasi: Situngkir/Samosir | Jenis: Wisata Alam | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Pantai Sigur-gur', 'Lokasi: Simanindo/Samosir | Jenis: Wisata Alam | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Bukit Sibeabea', 'Lokasi: Harian/Samosir | Jenis: Wisata Alam dan Wisata Religi | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Aek Sipitu Dai', 'Lokasi: Sianjur mula-mula/Samosir | Jenis: Wisata budaya dan Wisata Religi | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Batu Sawan', 'Lokasi: Sianjur mula-mula /Samosir | Jenis: Wisata budaya | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Air Terjun Naisogop', 'Lokasi: Sianjur mula-mula /Samosir | Jenis: Wisata alam | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Menara Pandang Tele', 'Lokasi: Harian/Samosir | Jenis: Wisata alam | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Kawasan Sigulatti-Pusat Informasi Geopark', 'Lokasi: Sianjur mula-mula /Samosir | Jenis: Wisata budaya | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Ruma Parsaktian Guru Tatea Bulan', 'Lokasi: Sianjur mula-mula /Samosir | Jenis: Wisata Budaya dan wisata religi | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Bukit Holbung', 'Lokasi: Dolokraja/Samosir | Jenis: Wisata alam | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Pemandian Aek Rangat', 'Lokasi: Pangururan/Samosir | Jenis: Wisata alam | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Sitalmaktalmak', 'Lokasi: Sihotang/Samosir | Jenis: Wisata alam | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Kawasan Hutan Pinus', 'Lokasi: Harian/Samosir | Jenis: Wisata alam | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Wetland Biocord-Putri Lopian (DLH)', 'Lokasi: Pangururan/Samosir | Jenis: Wisata alam | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Kampung Tenun Lumban Suhi', 'Lokasi: Pangururan/ Samosir | Jenis: Wisata Belanja | Wilayah: Polres Samosir | Keterangan: Kawasan Ekonomi Khusus'),
('Pantai Sibolazi', 'Lokasi: Simanindo/Samosir | Jenis: Wisata alam | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Pantai Langat', 'Lokasi: Simanindo/Samosir | Jenis: Wisata alam | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Sijukjuk Hill', 'Lokasi: Harian boho/Samosir | Jenis: Wisata alam | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Bona Bona Hill', 'Lokasi: Harian boho/Samosir | Jenis: Wisata alam | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Hidden Beach', 'Lokasi: Simanindo/Samosir | Jenis: Wisata alam | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Kuburan diatas pohon', 'Lokasi: Tomok/Samosir | Jenis: Wisata Religi | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Objek Wisata Lagundi', 'Lokasi: Onanrunggu/Samosir | Jenis: Wisata Alam | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Museum Huta Bolon', 'Lokasi: Simanindo/Samosir | Jenis: Wisata Budaya | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Tugu toga Sinaga', 'Lokasi: Palipi/Samosir | Jenis: Wisata Budaya | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Danau Sidihoni', 'Lokasi: Pangururan/Samosir | Jenis: Wisata Alam | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Aek Sipaloinggang', 'Lokasi: Pangururan/Samosir | Jenis: Wisata Alam | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Aek Tawar', 'Lokasi: Ronggur Nihuta/Samosir | Jenis: Wisata Alam | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Padan togu', 'Lokasi: Ronggur Nihuta/Samosir | Jenis: Wisata Budaya | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Wisata Pangaloan', 'Lokasi: Nainggolan/Samosir | Jenis: Wisata Budaya | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Batu Guru', 'Lokasi: Nainggolan/Samosir | Jenis: Wisata Alam | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Mual Boru Saroding', 'Lokasi: Sitio-tio/Samosir | Jenis: Wisata Budaya | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Dolok Sipatungan', 'Lokasi: Sitio-tio/ Samosir | Jenis: Wisata alam | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Batu Parpadanan', 'Lokasi: Sitio-tio/ Samosir | Jenis: Wisata alam | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Mual Boru Pareme', 'Lokasi: Sitio-tio/Samosir | Jenis: Wisata Budaya | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Parhutaan Siraja Lottung', 'Lokasi: Sitio-tio/Samosir | Jenis: Wisata Budaya | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Rumah Parsaktian Lumban Raja', 'Lokasi: Onanrunggu/Samosir | Jenis: Wisata Budaya | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Mual Tornong Parhuta hutaan', 'Lokasi: Sitio-tio/ Samosir | Jenis: Wisata Budaya | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Agrowisata Raptamawijaya', 'Lokasi: Ronggur Nihuta/Samosir | Jenis: Agrowisata | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Batu Maroppa', 'Lokasi: Sitio-tio/Samosir | Jenis: Wisata Alam | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Wisata Leluhur Gunung Uluh Darat', 'Lokasi: Sitio-tio/Samosir | Jenis: Wisata alam dan Budaya | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Aek Bunga-bunga', 'Lokasi: Sianjur mula-mula/Samosir | Jenis: Wisata Alam | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Tulas View', 'Lokasi: Pangururan/Samosir | Jenis: Wisata Alam | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Perkampungan Siraja Batak', 'Lokasi: Sianjur Mula-mula/Samosir | Jenis: Wisata Budaya | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Kawasan Wisata Desa Siboro', 'Lokasi: Sianjur Mula-mula/Samosir | Jenis: Wisata alam | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Air Terjun Sampuran Pangaribuan', 'Lokasi: Palipi/Samosir | Jenis: Wisata alam | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Siborbor Rinabolak', 'Lokasi: Onanrunggu/Samosir | Jenis: Wisata alam | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Eco Village Silimalombu', 'Lokasi: Onanrunggu/Samosir | Jenis: Agrowisata | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Hariara Bolon Sukkean', 'Lokasi: Onanrunggu/Samosir | Jenis: Wisata Religi | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Liang Sipogu', 'Lokasi: Simanindo/Samosir | Jenis: Wisata Alam | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Pea Porohan', 'Lokasi: Ronggur Nihuta/Samosir | Jenis: Wisata alam | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Goa Lumban Dolok', 'Lokasi: Ronggur Nihuta/Samosir | Jenis: Wisata Alam | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Sampuran Bona-bona', 'Lokasi: Ronggur Nihuta/Samosir | Jenis: Wisata Alam | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Sampuran Sigaol', 'Lokasi: Ronggur Nihuta/Samosir | Jenis: Wisata Alam | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Aek Marulak', 'Lokasi: Ronggur Nihuta/Samosir | Jenis: Wisata Alam | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Batu Rante', 'Lokasi: Palipi/Samosir | Jenis: Wisata Budaya | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Hariara Maranak', 'Lokasi: Palipi/Samosir | Jenis: Wisata Budaya | Wilayah: Polres Samosir | Keterangan: Objek Wisata Biasa'),
('Jembatan tano Ponggol', 'Lokasi: Kec. Pangururan | Jenis: Wisata Alam | Wilayah: Polres Samosir | Keterangan: Objek Vital nasional'),
('Water Front City', 'Lokasi: Kec. Pangururan | Jenis: Wisata Alam | Wilayah: Polres Samosir | Keterangan: Objek Vital nasional');
